### ISSUE TITLE
CognitiveCam keeps stopping

### ISSUE THREAD

**Issue by chitz1** [SaiKeshav/CognitiveCam#1]
hello sir,
when i tried to run app in my mobile it opens and says welcome message and wen i tap it says image captured then i asks question then tap again then i get error as cognitivecam keeps stopping . could you help me please and also i cant generate apk because it throws following error please sir help me . 

The project is using an unsupported version of Gradle.
Please point to a supported Gradle version in the project's Gradle settings or in the project's Gradle wrapper (if applicable.)
Fix Gradle wrapper and re-import project
Open Gradle wrapper properties
Gradle settings
------------------------------------------------------------------------------------------
Here is my manifest file 

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.android.camera2basic">

    <uses-permission android:name="android.permission.INTERNET"/>

    <uses-permission android:name="android.permission.CAMERA" />

    <uses-feature android:name="android.hardware.camera" android:required="true" />
    <uses-feature android:name="android.hardware.camera.autofocus" />

    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />

    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

    <application android:allowBackup="true"
        android:label="@string/app_name"
        android:icon="@drawable/ic_launcher"
        android:theme="@style/MaterialTheme">

        <activity android:name=".CameraActivity"
                  android:label="@string/app_name">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>
-------------------------------------------------------------------------------------------------
and here is my build.gradle(module:application) file 

pply plugin: 'com.android.application'

repositories {
    jcenter()
}

dependencies {
    compile 'com.android.support:support-v4:23.3.0'
    compile 'com.android.support:support-v13:23.3.0'
    compile 'com.android.support:cardview-v7:23.3.0'
    compile 'com.android.support:appcompat-v7:23.0.0'
    compile 'com.ibm.watson.developer_cloud:java-sdk:3.7.2'

    compile files('D:/AndroidProjects/CognitiveCam/CognitiveCam/libs/java-sdk-3.3.0-jar-with-dependencies.jar')
    compile 'id.zelory:compressor:1.0.2'
    compile files('libs/java-sdk-3.3.0-jar-with-dependencies.jar')
}

// The sample build uses multiple directories to
// keep boilerplate and common code separate from
// the main sample code.
List<String> dirs = [
    'main',     // main sample code; look here for the interesting stuff.
    'common',   // components that are reused by multiple samples
    'template'] // boilerplate code that is generated by the sample template process

android {
    compileSdkVersion 23
    buildToolsVersion '29.0.1'

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 23
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }

    sourceSets {
        main {
            dirs.each { dir ->
                java.srcDirs "src/${dir}/java"
                res.srcDirs "src/${dir}/res"
            }
        }
        androidTest.setRoot('tests')
        androidTest.java.srcDirs = ['tests/src']

    }

}
-------------------------------------------------------------------------
my Grale version is 5.1.1 and my android plugin version is 2.1.3 
 please help me !

**Comment by SaiKeshav** [comment]
I am sorry but we are no longer maintaining this code...
